language: python
sudo: false

matrix:
  include:
  - env: TOXENV=py36
    python: "3.6"
  - env: TOXENV=pre-commit
    python: "3.6"
install: pip install tox coveralls
script: tox
after_success: coveralls
